name: UI Tests

on:
  push:
    branches: [ dev ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: UI tests results
        uses: actions/upload-artifact@v1
        with:
          name: ui-tests-results
          path: app/build/reports/androidTests/connected/index.html
